services:
  - type: web
    name: crop-price-forecast
    env: python
    buildCommand: pip install -r requirements.txt && python generate_data.py && python model/train.py
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.enableCORS false --server.enableXsrfProtection false
    envVars:
      - key: GROQ_API_KEY
        sync: false
